### ISSUE TITLE
ArgumentError: this IO is already registered with selector

### ISSUE THREAD

**Issue by dblock** [slack-ruby/slack-api-explorer#6]
```
I, [2017-03-15T03:48:24.903675 #171]  INFO -- : HELP: name=Artsy, id=T02531TU5 - U02BEFY4U
I, [2017-03-15T03:48:33.514073 #171]  INFO -- : SLACK: name=Artsy, id=T02531TU5 - channels
I, [2017-03-15T03:48:41.058946 #171]  INFO -- : SLACK: name=Artsy, id=T02531TU5 - channels list
E, [2017-03-15T03:48:46.014359 #171] ERROR -- : Actor crashed!
ArgumentError: this IO is already registered with selector
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:42:in `register'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:42:in `wait'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/reactor.rb:26:in `wait_writable'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io.rb:66:in `wait_writable'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:34:in `wait_writable'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:64:in `rescue in block in syswrite'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:61:in `block in syswrite'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:390:in `synchronize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:59:in `syswrite'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:356:in `do_write'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-io-0.17.3/lib/celluloid/io/stream.rb:250:in `write'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/concurrency/celluloid.rb:62:in `write'
	/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:228:in `send_frame'
	/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver/hybi.rb:191:in `frame'
	/app/vendor/bundle/ruby/2.3.0/gems/websocket-driver-0.6.5/lib/websocket/driver.rb:111:in `text'
	/app/vendor/bundle/ruby/2.3.0/gems/slack-ruby-client-0.8.0/lib/slack/real_time/socket.rb:21:in `send_data'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
	/app/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by dblock** [comment]
No longer using celluloid.
